# Generated by Django 4.0.4 on 2022-04-23 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeatReceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make_time', models.IntegerField(null=True)),
                ('hard_level', models.CharField(choices=[('easy', 'Easy to make'), ('medium', 'Not so hard'), ('hard', 'A bit harder than others receipes')], max_length=6)),
                ('kcal', models.IntegerField(null=True)),
                ('receipe', models.TextField(null=True)),
                ('alergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('for_children', models.BooleanField(default=True)),
                ('make_date', models.DateField()),
                ('days_from_add', models.IntegerField()),
                ('meat_kind', models.CharField(max_length=200)),
                ('meat_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VegeReceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make_time', models.IntegerField(null=True)),
                ('hard_level', models.CharField(choices=[('easy', 'Easy to make'), ('medium', 'Not so hard'), ('hard', 'A bit harder than others receipes')], max_length=6)),
                ('kcal', models.IntegerField(null=True)),
                ('receipe', models.TextField(null=True)),
                ('alergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('for_children', models.BooleanField(default=True)),
                ('make_date', models.DateField()),
                ('days_from_add', models.IntegerField()),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
