# Generated by Django 4.0.4 on 2022-06-22 22:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('change_book', 'Can change book'),),
            },
        ),
        migrations.CreateModel(
            name='CookBookReceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField(choices=[(1, 'Bad'), (2, 'Lower Medium'), (3, 'Medium'), (4, 'Lower Good'), (5, 'Good'), (6, 'Excelent')])),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.cookbook')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make_time', models.IntegerField(null=True)),
                ('hard_level', models.CharField(choices=[('easy', 'Easy to make'), ('medium', 'Not so hard'), ('hard', 'A bit harder than others receipes')], max_length=6)),
                ('kcal', models.IntegerField(null=True)),
                ('text_receipe', models.TextField()),
                ('alergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('for_children', models.BooleanField(default=True)),
                ('make_date', models.DateField(blank=True, null=True)),
                ('days_from_add', models.DurationField(blank=True, null=True)),
                ('cookbook', models.ManyToManyField(through='receipe.CookBookReceipe', to='receipe.cookbook')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.country')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipe.picture', to_field='image_no')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BreakfastReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('sweet', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('dairy', 'Including dairy'), ('meat', 'Including meat')], max_length=6)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.CreateModel(
            name='DinnerReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('before_bed_time', models.TimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.CreateModel(
            name='LunchReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('digest_hard', models.BooleanField(default=False)),
                ('to_microwave', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.CreateModel(
            name='MeatReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('meat_kind', models.CharField(blank=True, max_length=200, null=True)),
                ('meat_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.CreateModel(
            name='SnackReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('sweet', models.BooleanField()),
                ('boiled', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.CreateModel(
            name='TagCountry',
            fields=[
                ('country_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.country')),
                ('tag_text', models.CharField(max_length=300)),
                ('name_in_country_language', models.CharField(max_length=300)),
                ('name_in_english', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('receipe.country', models.Model),
        ),
        migrations.CreateModel(
            name='VegeReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('protein_type', models.CharField(max_length=200, null=True)),
                ('vege_type', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.AddField(
            model_name='cookbookreceipe',
            name='receipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.receipe'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_country_id', to='receipe.tagcountry'),
        ),
    ]
