# Generated by Django 4.0.4 on 2022-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatreceipe',
            name='days_from_add',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vegereceipe',
            name='days_from_add',
            field=models.IntegerField(null=True),
        ),
    ]
