# Generated by Django 4.0.4 on 2022-04-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_alter_meatreceipe_days_from_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meatreceipe',
            name='days_from_add',
        ),
        migrations.RemoveField(
            model_name='vegereceipe',
            name='days_from_add',
        ),
    ]
