# Generated by Django 4.0.4 on 2022-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_remove_meatreceipe_days_from_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatreceipe',
            name='days_from_add',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='vegereceipe',
            name='days_from_add',
            field=models.DurationField(null=True),
        ),
    ]
