# Generated by Django 4.0.4 on 2022-08-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0004_remove_meatreceipe_cookbook_receipe_cookbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='tag',
        ),
        migrations.DeleteModel(
            name='TagCountry',
        ),
    ]
