# Generated by Django 4.0.4 on 2022-05-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0004_meatreceipe_days_from_add_vegereceipe_days_from_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeatReceipe',
        ),
        migrations.DeleteModel(
            name='VegeReceipe',
        ),
    ]
