# Generated by Django 4.0.4 on 2022-05-27 16:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('receipe', '0005_delete_meatreceipe_delete_vegereceipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make_time', models.IntegerField(null=True)),
                ('hard_level', models.CharField(choices=[('easy', 'Easy to make'), ('medium', 'Not so hard'), ('hard', 'A bit harder than others receipes')], max_length=6)),
                ('kcal', models.IntegerField(null=True)),
                ('text_receipe', models.TextField(null=True)),
                ('alergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('for_children', models.BooleanField(default=True)),
                ('make_date', models.DateField()),
                ('days_from_add', models.DurationField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='VegeReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
    ]
