# Generated by Django 4.0.4 on 2022-08-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0005_remove_receipe_tag_delete_tagcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=300)),
                ('name_in_country_language', models.CharField(max_length=300)),
                ('name_in_english', models.CharField(max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='receipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_country_id', to='receipe.tagcountry'),
        ),
    ]
