# Generated by Django 4.0.4 on 2022-05-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('meat_kind', models.CharField(max_length=200)),
                ('meat_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('meat_receipe', models.ManyToManyField(to='receipe.meatreceipe')),
            ],
        ),
        migrations.AddField(
            model_name='meatreceipe',
            name='meat_tag',
            field=models.ManyToManyField(to='receipe.tag'),
        ),
    ]
