# Generated by Django 4.0.4 on 2022-05-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0007_meatreceipe_tag_meatreceipe_meat_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PictureReceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.picture', to_field='image_no')),
                ('to_receipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.receipe')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='to_receipe',
            field=models.ManyToManyField(through='receipe.PictureReceipe', to='receipe.receipe'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='to_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipe.picture', to_field='image_no'),
        ),
    ]
