# Generated by Django 4.0.4 on 2022-05-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0009_cookbook_cookbookreceipe_cookbook_to_receipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='cookbook',
            name='to_receipe',
        ),
        migrations.AddField(
            model_name='receipe',
            name='to_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='receipe.country'),
        ),
    ]
