# Generated by Django 4.0.4 on 2022-05-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0010_country_remove_cookbook_to_receipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryReceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.country')),
                ('to_receipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.receipe')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='to_receipe',
            field=models.ManyToManyField(to='receipe.countryreceipe'),
        ),
    ]
