# Generated by Django 4.0.4 on 2022-05-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0012_remove_country_to_receipe_delete_countryreceipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meatreceipe',
            old_name='meat_tag',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meat_receipe',
        ),
    ]
