# Generated by Django 4.0.4 on 2022-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0013_rename_meat_tag_meatreceipe_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='to_picture',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='to_receipe',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PictureReceipe',
        ),
    ]
