# Generated by Django 4.0.4 on 2022-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0016_rename_to_country_receipe_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='receipe',
        ),
        migrations.AddField(
            model_name='receipe',
            name='cookbook',
            field=models.ManyToManyField(through='receipe.CookBookReceipe', to='receipe.cookbook'),
        ),
    ]
