# Generated by Django 4.0.4 on 2022-05-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0017_remove_cookbook_receipe_receipe_cookbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.country'),
        ),
    ]
