# Generated by Django 4.0.4 on 2022-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0018_alter_receipe_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='picture',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
