# Generated by Django 4.0.4 on 2022-05-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0019_remove_receipe_picture_alter_picture_image_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipe.picture', to_field='image_no'),
        ),
    ]
