# Generated by Django 4.0.4 on 2022-05-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0022_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbookreceipe',
            name='cookbook',
        ),
        migrations.RemoveField(
            model_name='cookbookreceipe',
            name='receipe',
        ),
        migrations.RemoveField(
            model_name='meatreceipe',
            name='receipe_ptr',
        ),
        migrations.RemoveField(
            model_name='meatreceipe',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='cookbook',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='country',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='vegereceipe',
            name='receipe_ptr',
        ),
        migrations.DeleteModel(
            name='CookBook',
        ),
        migrations.DeleteModel(
            name='CookBookReceipe',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='MeatReceipe',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='VegeReceipe',
        ),
    ]
