# Generated by Django 4.0.4 on 2022-05-28 19:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('receipe', '0023_remove_cookbookreceipe_cookbook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CookBookReceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField(choices=[(1, 'Bad'), (2, 'Lower Medium'), (3, 'Medium'), (4, 'Lower Good'), (5, 'Good'), (6, 'Excelent')])),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.cookbook')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make_time', models.IntegerField(null=True)),
                ('hard_level', models.CharField(choices=[('easy', 'Easy to make'), ('medium', 'Not so hard'), ('hard', 'A bit harder than others receipes')], max_length=6)),
                ('kcal', models.IntegerField(null=True)),
                ('text_receipe', models.TextField(null=True)),
                ('alergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('for_children', models.BooleanField(default=True)),
                ('make_date', models.DateField()),
                ('days_from_add', models.DurationField(null=True)),
                ('cookbook', models.ManyToManyField(through='receipe.CookBookReceipe', to='receipe.cookbook')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.country')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipe.picture', to_field='image_no')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VegeReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
        migrations.AddField(
            model_name='cookbookreceipe',
            name='receipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipe.receipe'),
        ),
        migrations.CreateModel(
            name='MeatReceipe',
            fields=[
                ('receipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.receipe')),
                ('meat_kind', models.CharField(max_length=200)),
                ('meat_type', models.CharField(max_length=200)),
                ('tag', models.ManyToManyField(to='receipe.tag')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('receipe.receipe',),
        ),
    ]
