# Generated by Django 4.0.4 on 2022-06-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0024_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastReceipe',
            fields=[
                ('meatreceipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.meatreceipe')),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
                ('sweet', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('dairy', 'Including dairy'), ('meat', 'Including meat')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
            bases=('receipe.meatreceipe', 'receipe.receipe'),
        ),
        migrations.CreateModel(
            name='DinnerReceipe',
            fields=[
                ('meatreceipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.meatreceipe')),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
                ('before_bed_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('receipe.meatreceipe', 'receipe.receipe'),
        ),
        migrations.CreateModel(
            name='LunchReceipe',
            fields=[
                ('meatreceipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.meatreceipe')),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
                ('digest_hard', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('receipe.meatreceipe', 'receipe.receipe'),
        ),
        migrations.CreateModel(
            name='SnackReceipe',
            fields=[
                ('meatreceipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receipe.meatreceipe')),
                ('protein_type', models.CharField(max_length=200)),
                ('vege_type', models.CharField(max_length=200)),
                ('sweet', models.BooleanField()),
                ('boiled', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('receipe.meatreceipe', 'receipe.receipe'),
        ),
        migrations.DeleteModel(
            name='VegeReceipe',
        ),
    ]
