# Generated by Django 4.0.4 on 2023-01-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=500)),
                ('rate', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=500)),
                ('alcohol', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceipeCookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('make_date', models.DateField(blank=True, null=True)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.cookbook')),
                ('receipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.receipe')),
            ],
        ),
    ]
