# Generated by Django 4.0.4 on 2023-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='receipe',
            field=models.ManyToManyField(through='cookbook.ReceipeCookbook', to='cookbook.receipe'),
        ),
    ]
